[package]
name = "bump_recycle"
version = "0.1.0-alpha"
edition = "2024"
license = "MIT OR Apache-2.0"
categories = ["memory-management"]
repository = "https://github.com/tower120/bump_recycle"
keywords = ["allocator", "arena", "bump", "reuse", "recycle"]
description = "Bump allocator that can reuse deallocated memory."

[features]
allocator_api = []

[dependencies]

[dev-dependencies]
itertools = "0.15"
criterion = "0.8.2"
bumpalo = {version = "=3.20.3", features=["allocator_api"]}

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[[bench]]
name = "alloc"
harness = false

[[bench]]
name = "vec"
harness = false